import { PageHeader } from '@/components/page-header'
import { Activity } from 'lucide-react'

/**
 * Behavioral Alerts view. Events are generated by the PetPulse Edge AI
 * service (YOLO26n perception) and delivered to the owner's mobile app
 * via FCM. The vet portal shows audit status on each pet's health record
 * row (owner_notified flag). A full vet-facing alert timeline is a
 * post-submission enhancement.
 */
export default function AlertsPage() {
  return (
    <>
      <PageHeader
        title="Behavioural Alerts"
        description="Real-time anomaly events from the edge AI monitoring system."
      />
      <div className="glass mt-6 flex flex-col items-center justify-center rounded-2xl px-8 py-16 text-center">
        <span className="flex size-14 items-center justify-center rounded-2xl border border-white/10 bg-white/5 text-muted-foreground">
          <Activity className="size-7" aria-hidden="true" />
        </span>
        <h2 className="mt-4 text-lg font-semibold">
          Alerts delivered to the owner app
        </h2>
        <p className="mt-2 max-w-md text-sm text-muted-foreground">
          The YOLO26n edge service detects pacing and prolonged-waiting
          episodes and dispatches a behavioural event webhook to the API.
          The owner receives an FCM push notification immediately; the{' '}
          <code className="rounded bg-white/5 px-1 py-0.5 font-mono text-xs">
            owner_notified
          </code>{' '}
          flag on each event row records confirmed delivery.
        </p>
        <p className="mt-4 text-xs text-muted-foreground">
          Per-patient alert timelines are visible on the patient&apos;s health
          record, and a dedicated vet-facing alert feed is a planned
          post-submission enhancement.
        </p>
      </div>
    </>
  )
}